language: python
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  username: "__token__"
  skip_existing: true
  on:
    tags: true
  password:
    secure: ps4wxK3Jc2SAV1QX6dKtufLobC9dmYzgNj0a4WBm8SQkAntLmN2uGzYrwmtJzhPefEX2vsedWxC0GTf+527psmThDc7nvWaTO6YVCMZPfb/V9ofU3qPrCRgNZ/wjAMotSCZZM5BvF274xsHyjuNbdgMTFvhab4/fQINMO/d16LESY5vz1csZ/HyZf9xRqnIgLzPjmR0ghLw5rnGPJ6WawSpfOkdFUfFk4NGfR88uywJagCwgoWNXH4ClZ81prfrz0uNPOkm7qOa41sgAaLRq2E2qxzHjojwYkFdZsMl1j+RUD2Lx5QE3ceMkvRYwb+uZInQifKc8F9hIhpdpvICfgst5tVIwwkzWBat3vkQjltnzXO80s0GvNjapcWxBXrq9g8dwOYMg8THIcU58rgDKgyH1rEGRh4tk5Y7XMzglM39qbjhuSpcN0NAohje5E118mC19m/+l4OYHwg0+9C/Ro4qxxCjm81d+GwIvs4wyjVTTYwTQbeZ+dUNBpOLjVOfCAM4AZHPk+VSGWBjd+j3VG06bzyqCDNcGXdNs53SeARI+TqNlKa2nhPB3humFb2sbpINGadOm7vXGwnrf+I1s/A4VTrCOLxOsH/+xwtOIhNRbUmxEWl5RXV3gX8F71M37FH25UDfoIB84mmo61YvUB+LTGqGAXeMt4UwU1lBDkWc=